export const SET_THEATER = "SET_THEATER";
export const GET_THEATER_INFO = "GET_THEATER_INFO";
export const GET_THEATER_BY_ID = "GET_THEATER_BY_ID";
export const GET_THEATER_INFO_DEBASE_ON_SYSTEM =
  "GET_THEATER_INFO_DEBASE_ON_SYSTEM";
