export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const FETCH_NOW_SHOWING = "FETCH_NOW_SHOWING";
export const FETCH_COMMING_SOON = "FETCH_COMMING_SOON";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_PAGINATION = "GET_MOVIE_PAGINATION";
export const RESET_LIST_SEATS = "RESET_LIST_SEATS";
export const GET_ERROR = "GET_ERROR";
