export const SET_DETAIL_ROOM = "SET_DETAIL_ROOM";
export const BOOKING_TICKET = "BOOKING_TICKET";
export const COMPLETE_BOOKING_TICKET = "COMPLETE_BOOKING_TICKET";
export const BOOKING_SEAT = "BOOKING_SEAT";
export const REMOVE_SEAT = "REMOVE_SEAT";
